import {initial,advance,parseOath,setOath,nearest,distance,connections,oathTypes,oathActive,metricNames,citizenEvents,applyAiTurn} from './world.js';
const $=id=>document.getElementById(id);let state=initial(),selected=state.current,pending=null,busy=false;
function text(tag,value){const n=document.createElement(tag);n.textContent=value;return n;}function lines(id,items){$(id).replaceChildren(...items.map(([tag,t])=>text(tag,t)));}
function mapLabels(cities){const used=[];return cities.map(c=>{let label;for(const [dx,dy]of [[0,0],[0,-70],[0,70],[110,0],[-110,0],[110,-70],[-110,70]]){const x=Math.max(65,Math.min(935,c.x+dx)),y=Math.max(55,Math.min(520,c.y+dy));if(!used.some(p=>Math.abs(p.x-x)<125&&Math.abs(p.y-y)<95)){label={x,y};break;}}label??={x:c.x,y:c.y};used.push(label);return {...c,label};});}
function render(){const current=state.cities.find(c=>c.id===state.current),city=state.cities.find(c=>c.id===selected),next=nearest(state);
 $('stats').innerHTML=[['世界时间',`${state.turn}/60`],['当前治理',current.name],['剩余任期',state.ended?'已结束':`${6-state.turn%6}轮`],['下一站',state.ended?'世界已结算':next.name]].map(([a,b])=>`<div class="stat"><span>${a}</span><b>${b}</b></div>`).join('');$('turn').textContent='城市位置随每次行动变化';const links=connections(state).filter(p=>p.type!=='隔绝');
 $('map').innerHTML=`<defs><pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M50 0H0V50" fill="none" stroke="#8fb5ba" stroke-opacity=".08"/></pattern></defs><rect width="1000" height="600" fill="url(#grid)"/><text x="35" y="50" fill="#879f9f" font-size="15" letter-spacing="5">混 沌 之 海</text>${links.map(p=>{const a=state.cities.find(c=>c.id===p.a),b=state.cities.find(c=>c.id===p.b);return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${p.type==='邻接'?'#83b995':'#7faab9'}" stroke-width="2" opacity=".35"/>`;}).join('')}${mapLabels(state.cities).map(c=>`<line x1="${c.origin.x}" y1="${c.origin.y}" x2="${c.x}" y2="${c.y}" stroke="#c2c9ba" opacity=".45" stroke-dasharray="4 5"/><circle cx="${c.origin.x}" cy="${c.origin.y}" r="4" fill="#97a9a8"/><circle cx="${c.x}" cy="${c.y}" r="7" fill="${c.id===state.current?'#e2bd79':'#91b6b1'}"/><line x1="${c.x}" y1="${c.y}" x2="${c.label.x}" y2="${c.label.y}" stroke="#91b6b1" stroke-opacity=".5"/><g class="city-node" data-city="${c.id}" tabindex="0" role="button" aria-label="查看${c.name}" transform="translate(${c.label.x},${c.label.y})"><ellipse rx="54" ry="36" fill="${c.id===state.current?'#43594c':'#304849'}" stroke="${c.id===selected?'#e2bd79':'#668185'}" stroke-width="2"/><text text-anchor="middle" y="6" fill="#ede8dc" font-size="20">${c.name}</text><text text-anchor="middle" y="60" fill="#d2c6a8" font-size="13">${c.oath?(oathActive(c)?'✦誓约生效':'◇誓约休眠'):c.id===state.current?'当前任期':'尚未立誓'}</text></g>`).join('')}`;
 lines('scene',[['h3',`${city.name}${city.id===state.current?'·当前治理':'·远方城市'}`],['p',`${city.lore}。位置(${Math.round(city.x)},${Math.round(city.y)})；距当前城${Math.round(distance(current,city))}。曾治理${city.visits}次。`],['p',Object.entries(metricNames).map(([k,n])=>`${n} ${city[k]}/100`).join(' · ')],['p',city.oath?`誓约：「${city.oath.text}」／${oathTypes[city.oath.type]}。${city.oath.explanation}。当前${oathActive(city)?'生效':'条件不足，暂时休眠'}。`:'此城尚未点燃誓约火炬。']]);
 $('actions').innerHTML=[['farm','组织耕种','粮食+7，生态−2'],['mediate','调解争端','安定+6，粮食−1'],['build','建设集市','繁荣+6，生态−3'],['restore','修复林地','生态+6，繁荣−2'],['observe','观察世界','推进一轮，观察漂移']].map(([a,n,h])=>`<button data-action="${a}" ${busy||state.ended||selected!==state.current?'disabled':''}>${n}<small>${h}</small></button>`).join('');
 for(const id of ['judge','oath-text','ai','reset'])$(id).disabled=busy||(id!=='reset'&&(state.ended||selected!==state.current));$('confirm').disabled=busy||state.ended||selected!==state.current;$('confirm').hidden=!pending;
 lines('events',[...state.events.flatMap(e=>[['h3',`${e.city}·${e.name}`],['p',e.text],['p',`条件：${e.condition}；影响：${Object.entries(e.effect).map(([k,v])=>`${metricNames[k]} ${v>0?'+':''}${v}`).join('，')||'无数值变化'}`]]),['p',state.interactions?.slice(0,6).join('\n')||'等待第一次行动，城市将在六十轮中逐渐改变关系。']]);$('event-guide').replaceChildren(...citizenEvents.map(e=>text('p',`${e.name}：${e.condition}。${e.repeat?'可重复':'每城最多一次'}。`)));$('log').replaceChildren(...state.history.filter(h=>!h.cities).slice(-30).reverse().map(h=>text('li',`第${h.turn}轮·${h.kind}：${h.text}`)));
 $('ending').hidden=!state.ended;if(state.ending)lines('ending',[['p',`世界结算·${state.ending.source}`],['h2',state.ending.title],['p',state.ending.text],['h3','历史依据'],...state.ending.evidence.map(e=>['p',e])]);}
async function api(task,input){const r=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,...input}),signal:AbortSignal.timeout(35000)});const d=await r.json();if(!r.ok)throw new Error(d.error||'接口请求失败');return d;}
function clearPending(){pending=null;$('oath-preview').replaceChildren();$('confirm').hidden=true;}
$('oath-text').oninput=clearPending;$('ai').onchange=()=>{clearPending();$('ai-status').textContent=$('ai').checked?'真实AI模式：请求失败时明确回退到本地模拟。':'本地模拟模式。';};
$('judge').onclick=async()=>{if(busy)return;busy=true;render();clearPending();try{const raw=$('oath-text').value.trim();if(!raw||raw.length>160)throw new Error('请填写1–160字的誓约。');if($('ai').checked){try{const d=await api('oath',{state,text:raw});if(!d.accepted){const error=new Error(d.reason||'誓约不可执行');error.rejected=true;throw error;}pending={...d.oath,text:raw,source:'真实AI'};setOath(state,pending);$('ai-status').textContent='誓约条件由真实AI判定。';}catch(e){if(e.rejected)throw e;$('ai-status').textContent=`AI未生效：${e.message}。改用本地模拟。`;pending=parseOath(raw);}}else pending=parseOath(raw);const city=state.cities.find(c=>c.id===state.current);lines('oath-preview',[['h3',oathTypes[pending.type]],['p',pending.explanation],['p',`${pending.source}·当前${city[pending.condition.metric]>=pending.condition.min?'满足':'不满足'}实行条件。确认后替换本城旧誓约，不推进时间。`]]);}catch(e){pending=null;lines('oath-preview',[['p',e.message]]);}finally{busy=false;render();}};
$('confirm').onclick=()=>{try{if(!pending||busy)return;state=setOath(state,pending);clearPending();$('oath-text').value='';render();}catch(e){lines('oath-preview',[['p',e.message]]);}};
async function perform(action){if(busy||state.ended||selected!==state.current)return;busy=true;clearPending();render();const before=state;try{let next=advance(state,action);if($('ai').checked){try{const result=await api('turn',{before,state:next,action});next=applyAiTurn(next,result,before);$('ai-status').textContent='本轮真实AI已判定城市影响；指标变化限定在±3。';}catch(e){if(e.rejected)throw e;$('ai-status').textContent=`AI未生效：${e.message}；本轮使用本地规则。`;}if(next.ended){try{const ending=await api('ending',{state:next});next.ending={...ending,source:'真实AI'};}catch(e){$('ai-status').textContent=`最终AI结算未生效：${e.message}；显示本地历史结算。`;}}}state=next;selected=state.current;}catch(e){$('ai-status').textContent=e.message;}finally{busy=false;render();}}
document.addEventListener('click',e=>{const city=e.target.closest('[data-city]');if(city&&!busy){selected=city.dataset.city;clearPending();render();}const button=e.target.closest('[data-action]');if(button)perform(button.dataset.action);});document.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)&&e.target.matches('[data-city]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
$('reset').onclick=()=>{if(busy)return;state=initial();selected=state.current;clearPending();$('oath-text').value='';$('ai-status').textContent='新世界已生成，当前使用'+($('ai').checked?'真实AI接口（失败时明确回退）':'本地模拟')+'。';render();};$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`大陆漂移假说-第${state.turn}轮.json`;a.click();URL.revokeObjectURL(url);};render();
