import {cityActions,actionSpec,actionBlock,applyCityAction,barrierOutcome} from './barrier.js';
import test from 'node:test';import assert from 'node:assert/strict';import {initial,advance,setOath,parseOath,nearest,distance,applyAiTurn,connections,citizenEvents} from './world.js';
const play=(s,n,action='observe')=>{for(let i=0;i<n;i++)s=advance(s,action);return s;};
test('每次行动推进一轮，六城独立移动，输入不被修改',()=>{const s=initial(),n=advance(s,'observe');assert.equal(n.turn,1);assert.equal(s.turn,0);for(const c of n.cities){const old=s.cities.find(b=>b.id===c.id);assert.ok(distance(c,old)>0);}assert.notEqual(n.cities[0].x-s.cities[0].x,n.cities[1].x-s.cities[1].x);});
test('立誓不推进时间，替换仅影响当前城',()=>{let s=setOath(initial(),parseOath('此城永不缺粮'));s=setOath(s,parseOath('愿此城永远和平'));assert.equal(s.turn,0);assert.equal(s.cities[0].oath.type,'peace');assert.equal(s.cities[1].oath,null);});
test('坐标誓约固定立誓时的位置',()=>{let s=advance(initial(),'observe'),c=s.cities[0];s=setOath(s,parseOath('城市位置不变'));s=play(s,12);assert.equal(s.cities[0].x,c.x);assert.equal(s.cities[0].y,c.y);assert.ok(s.cities[0].oath);});
test('粮食誓约保护储备，条件不足休眠',()=>{let s=setOath(initial(),parseOath('永不缺粮')),n=advance(s,'observe');assert.ok(n.cities[0].food>=s.cities[0].food);s.cities[0].trade=0;s.cities[0].ecology=60;n=advance(s,'observe');assert.ok(n.cities[0].food<s.cities[0].food);});
test('第6轮按移动后的地图迁往最近其他城市，允许返回',()=>{let s=play(initial(),5);const old=s.current;s=advance(s,'observe');assert.notEqual(s.current,old);assert.equal(s.current,nearest(s,old).id);s=play(s,6);assert.equal(s.turn,12);assert.equal(s.current,nearest(s,s.history.filter(h=>h.kind==='行动').at(-1).city).id);});
test('最近城市可包括曾治理城市，不含当前城',()=>{const s=initial();s.visited=s.cities.map(c=>c.id);assert.notEqual(nearest(s).id,s.current);assert.ok(s.visited.includes(nearest(s).id));});
test('60轮才结算，保存60个快照与9次迁城',()=>{let s=play(initial(),59);assert.equal(s.ended,false);s=advance(s,'observe');assert.equal(s.ended,true);assert.ok(s.ending.text.includes('60次行动'));assert.equal(s.history.filter(h=>h.kind==='世界快照').length,60);assert.equal(s.history.filter(h=>h.kind==='迁城').length,9);assert.throws(()=>advance(s,'observe'));assert.throws(()=>setOath(s,parseOath('永不缺粮')));});
test('两种玩家策略产生不同结局指标，所有指标有界',()=>{const policy=action=>{let s=initial();for(let i=0;i<60;i++){const c=s.cities.find(c=>c.id===s.current);s=advance(s,actionBlock(c,action,null)?'observe':action);}return s;};const farm=policy('farm'),build=policy('build');assert.notDeepEqual(farm.ending.values,build.ending.values);for(const c of [...farm.cities,...build.cities])for(const k of ['food','peace','trade','ecology'])assert.ok(c[k]>=0&&c[k]<=100);});
test('历史保留每次誓约的文本、来源及操作',()=>{const s=advance(setOath(initial(),parseOath('守护森林')),'restore');assert.match(s.history.find(h=>h.kind==='立誓').text,/守护森林/);assert.equal(s.history.find(h=>h.kind==='行动').city,'ember');});
test('未知、多目标、空白誓约不被执行',()=>{for(const t of ['','无限资源','守护粮食与和平','大家幸福'])assert.throws(()=>parseOath(t));assert.throws(()=>setOath(initial(),{text:'x',type:'code',condition:{metric:'food',min:0}}));});
test('城市关系分为邻接、贸易与隔绝',()=>{const s=initial();s.cities[1].x=s.cities[0].x+100;s.cities[1].y=s.cities[0].y;assert.equal(connections(s).find(p=>p.a==='ember'&&p.b==='grove').type,'邻接');s.cities[1].x=s.cities[0].x+220;assert.equal(connections(s).find(p=>p.a==='ember'&&p.b==='grove').type,'贸易');});
test('AI影响有界且不能突破生效誓约',()=>{const s=setOath(initial(),parseOath('永不缺粮')),n=advance(s,'observe'),a=applyAiTurn(n,{summary:'邻城商路带来变化',effects:[{cityId:'ember',delta:{food:-3},reason:'测试保护'}]},s);assert.ok(a.cities[0].food>=s.cities[0].food);assert.throws(()=>applyAiTurn(n,{summary:'x',effects:[{cityId:'ember',delta:{food:100},reason:'x'}]},s));});
test('十种市民事件保留，每行动一个事件',()=>{assert.equal(citizenEvents.length,10);let s=initial();for(let i=0;i<10;i++){s=advance(s,'observe');assert.equal(s.events.length,1);}assert.equal(s.history.filter(h=>h.kind==='市民事件').length,10);});

test('快速漂移保持边界，城市距离关系确实改变',()=>{let s=initial();const first=advance(s,'observe');for(const c of first.cities)assert.ok(distance(c,s.cities.find(b=>b.id===c.id))>4);s=play(s,60);for(const c of s.cities){assert.ok(c.x>=65&&c.x<=935);assert.ok(c.y>=65&&c.y<=535);}assert.ok(s.history.some(h=>h.kind==='距离变化'));});

test('旧法则占用唯一槽，禁火减少生态支出但降低修复效率',()=>{let s=setOath(initial(),parseOath('城内不得燃火'));s=advance(s,'forest');assert.equal(s.cities[0].ecology,66);assert.equal(s.cities[0].peace,60);s=advance(s,'forge');assert.equal(s.cities[0].barrier,1);assert.equal(s.cities[0].ecology,66);s=setOath(s,parseOath('永不缺粮'));assert.equal(s.cities[0].oath.type,'food');assert.equal(s.turn,2);});
test('偿债路线需兼顾补给与调解，六轮可达共誓且保留迁城记录',()=>{let s=setOath(initial(),parseOath('所有债务必须偿还'));for(const a of ['forge','forest','farm','investigate','forge','investigate'])s=advance(s,a);const c=s.cities[0];assert.equal(c.barrier,6);assert.equal(c.barrierResults[0].title,'共誓');assert.equal(s.ended,false);assert.notEqual(s.current,c.id);assert.equal(s.history.filter(h=>h.kind==='屏障结果').length,1);assert.equal(s.cities.find(c=>c.id===s.current).barrier,0);});
test('强取光核可成孤光，资源不足与重复取回不耗回合',()=>{let s=initial();for(const a of ['reveal','forge','build','forge','observe','observe'])s=advance(s,a);assert.equal(s.cities[0].barrierResults[0].title,'孤光');s.current='ember';const before=structuredClone(s);assert.throws(()=>advance(s,'reveal'));assert.throws(()=>advance(s,'forge'),/已完成/);assert.deepEqual(s,before);s.cities[0].barrier=0;s.cities[0].trade=0;assert.throws(()=>advance(s,'forge'),/资源不足/);assert.equal(s.turn,6);});
test('禁谎改变统一安定资源，无独立信任或物资',()=>{const c=initial().cities[0];assert.ok(!('trust'in c)&&!('supply'in c));applyCityAction(c,'investigate','silence');assert.equal(c.peace,71);applyCityAction(c,'reveal','silence');assert.equal(c.peace,47);assert.equal(c.barrier,2);});
test('六十轮汇总十次任期与全部六城统一资源',()=>{const s=play(initial(),60);assert.equal(s.history.filter(h=>h.kind==='屏障结果').length,10);assert.equal(s.ending.barriers.length,6);assert.ok(s.ending.barriers.every(c=>c.title==='长夜'));assert.ok(s.ending.barriers.every(c=>Number.isFinite(c.peace)&&Number.isFinite(c.food)));});
test('所有行动先完整支付，不能透支且失败不修改状态',()=>{for(const action of Object.keys(cityActions)){const c=initial().cities[0],spec=actionSpec(action,null);for(const k of Object.keys(spec.cost)){const poor={...c,[k]:spec.cost[k]-1},before=structuredClone(poor);assert.throws(()=>applyCityAction(poor,action,null),/资源不足/);assert.deepEqual(poor,before);}}});
test('守护誓约与模拟AI都不能返还主动支付成本',()=>{for(const [oath,key]of [['守护贸易繁荣','trade'],['永不缺粮','food'],['守护森林','ecology'],['永远和平','peace']]){const s=setOath(initial(),parseOath(oath)),n=advance(s,'forge');assert.ok(n.cities[0][key]<s.cities[0][key]);const a=applyAiTurn(n,{summary:'测试主动成本边界',effects:[{cityId:'ember',delta:{[key]:-3},reason:'环境损失'}]},s);assert.ok(a.cities[0][key]>=s.cities[0][key]-n.lastAction.cost[key]);assert.ok(a.cities[0][key]<s.cities[0][key]);}});
test('商路收益每城每轮最多2，等待有持续粮食压力',()=>{const s=initial();for(const c of s.cities){c.x=100;c.y=100;c.ecology=50;c.eventSeen=['market'];}const n=advance(s,'observe');for(let i=0;i<6;i++)assert.ok(n.cities[i].trade-s.cities[i].trade<=2);const isolated=initial();const next=advance(isolated,'observe');assert.equal(next.cities[5].food,isolated.cities[5].food-2);});
test('共誓同时要求足够安定和粮食，屏障完成并非自动成功',()=>{assert.equal(barrierOutcome({barrier:6,peace:60,food:20}).title,'共誓');assert.equal(barrierOutcome({barrier:6,peace:59,food:50}).title,'孤光');assert.equal(barrierOutcome({barrier:6,peace:90,food:19}).title,'孤光');assert.equal(barrierOutcome({barrier:5,peace:90,food:90}).title,'长夜');});
test('模拟AI改变任期资源后复核屏障结果，原本地证据保留',()=>{let s=setOath(initial(),parseOath('所有债务必须偿还'));for(const a of ['forge','forest','farm','investigate','forge'])s=advance(s,a);const n=advance(s,'investigate');assert.equal(n.cities[0].barrierResults[0].title,'共誓');const after=applyAiTurn(n,{summary:'模拟边界测试',effects:[{cityId:'ember',delta:{peace:-3},reason:'模拟摩擦'}]},s);assert.equal(after.cities[0].barrierResults[0].title,'孤光');assert.equal(after.history.filter(h=>h.kind==='屏障结果').length,1);assert.equal(after.history.filter(h=>h.kind==='AI屏障复核').length,1);});
